# Generated by Django 5.1.3 on 2024-11-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0003_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
